server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myherochild
    username: myherochild
    password: myherochild

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    ignore-migration-patterns: "*:missing"

logging:
  level:
    org.hibernate.SQL: debug

app:
  security:
    admin-code: codAdmin
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      model: llama3:8b-instruct-q4_K_M

